apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: openjdk:11-jre-slim
          command: ["java", "-jar", "/app/hello-world-rest-api-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          hostPath:
            path: build/libs  # Replace with the path to your local directory containing the JAR file
